import { Octokit } from "octokit";

export interface DeployResult {
  url: string;
  repoName: string;
  message: string;
  isNewRepo: boolean;
}

export async function deployToGitHubPages(
  githubUsername: string,
  token: string,
  htmlContent: string,
  octokit: Octokit
): Promise<DeployResult> {
  const repoName = `${githubUsername}.github.io`;
  let isNewRepo = false;
  let sha: string | undefined;

  try {
    await octokit.rest.repos.get({
      owner: githubUsername,
      repo: repoName,
    });
    console.log(`Repository ${repoName} exists`);
  } catch (error) {
    const err = error as { status?: number; message?: string };
    if (err.status === 404) {
      console.log(`Creating repository ${repoName}...`);
      await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        description: "My portfolio website - Generated by GitStory",
        homepage: `https://${repoName}`,
        private: false,
        auto_init: true,
      });
      isNewRepo = true;

      // Wait for repo initialization
      await new Promise((resolve) => setTimeout(resolve, 2000));
    } else {
      throw new Error(
        `Failed to check repository: ${err.message || "Unknown error"}`
      );
    }
  }

  if (!isNewRepo) {
    try {
      const { data } = await octokit.rest.repos.getContent({
        owner: githubUsername,
        repo: repoName,
        path: "index.html",
      });

      if ("sha" in data && !Array.isArray(data)) {
        sha = data.sha;
        console.log(`Found existing index.html with SHA: ${sha}`);
      }
    } catch (error) {
      const err = error as { status?: number; message?: string };
      if (err.status === 404) {
        console.log("index.html doesn't exist, will create new file");
      } else {
        console.error("Error checking index.html:", err.message);
      }
    }
  }

  try {
    const base64Content = Buffer.from(htmlContent).toString("base64");

    await octokit.rest.repos.createOrUpdateFileContents({
      owner: githubUsername,
      repo: repoName,
      path: "index.html",
      message: sha
        ? "Update portfolio via GitStory"
        : "Create portfolio via GitStory",
      content: base64Content,
      sha: sha,
    });

    console.log(`Successfully ${sha ? "updated" : "created"} index.html`);
  } catch (error) {
    const err = error as { message?: string };
    throw new Error(
      `Failed to deploy portfolio: ${err.message || "Unknown error"}`
    );
  }

  const url = `https://${repoName}`;
  return {
    url,
    repoName,
    message: isNewRepo
      ? "Portfolio site created and deployed successfully! It may take 1-2 minutes to go live."
      : "Portfolio site updated successfully!",
    isNewRepo,
  };
}
