import type { Metadata } from "next";
import { AuthContextProvider } from "@/lib/auth/AuthProvider";
import { Geist, Geist_Mono } from "next/font/google";
import UserMenu from "@/components/UserMenu";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          {/* Header */}
          <header className="border-b border-gray-200">
            <div className="container mx-auto px-4 py-4 flex items-center justify-between">
              {/* Logo */}
              <Link href="/" className="text-2xl font-bold">
                GitStory
              </Link>

              {/* User Menu */}
              <UserMenu />
            </div>
          </header>

          {/* Main Content */}
          <main>{children}</main>

          {/* Footer (optional) */}
          <footer className="border-t border-gray-200 py-8 text-center text-sm text-gray-600">
            <p>Built with Kiro • © 2024 GitStory</p>
          </footer>
        </AuthContextProvider>
      </body>
    </html>
  );
}
